# Aufg 1
## a)

In [2]:
import numpy as np

passengers = np.array([2150,470,150])
planeSeats = np.array([[200,150,100],[50,30,20],[20,10,0]])



xstar = np.linalg.solve(planeSeats,passengers)


print("A, B, C")
print(xstar)


A, B, C
[4. 7. 3.]


## b)

In [3]:
passengers = np.array([1600,350,120])

xstar = np.linalg.solve(planeSeats,passengers)


print("A, B, C")
print(xstar)

A, B, C
[3. 6. 1.]


# Aufg 2

In [19]:
def S6_Aufg1(A, b):
    n = np.size(b)
    M = np.zeros((n, n + 1))

    M[0:n, 0:n] = np.copy(A)
    M[0:n, n] = np.copy(b)


    # Vorwärtselimination bring die Matrix in rechtsobere Dreiecksform

    # Rückwärtseinsetzen bringt das resultat auf x

    for j in range(0, n - 1):
        if M[j, j] == 0:
            i = j + 1
            while M[i, j] == 0:
                i = i + 1

            temp = np.copy(M[i, j : n + 1])
            M[i, j : n + 1] = M[j, j : n + 1]
            M[j, j : n + 1] = temp

        for i in range(j + 1, n):
            c = M[i, j] / M[j, j]
            M[i, j] = 0

            M[i, j + 1 : n + 1] = M[i, j + 1 : n + 1] - c * M[j, j + 1 : n + 1]
            


    x = np.zeros(n)
    for i in np.arange(n-1,-1,-1):
        x[i] = (M[i,n] - np.sum(M[i,i+1:n]*x[i+1:n]))/M[i,i]
    
    return M, x


# Aufg 3


In [20]:
A = np.array([[2,1,0],[4,0,-2],[1,2,4]])
b = np.array([1,1,0])

M, x = S6_Aufg1(A,b)

print(M)

print(x)

[[ 2.    1.    0.    1.  ]
 [ 0.   -2.   -2.   -1.  ]
 [ 0.    0.    2.5  -1.25]]
[ 0.   1.  -0.5]
